import type { Member, Project, Task, DashboardStats, TeamProgress, ActivityLog, Role } from '@/types';

// Mock Role
const adminRole: Role = {
  id: 'role-1',
  name: 'Admin',
  description: '시스템 관리자',
  isSystem: true,
  permissions: {
    project: { create: true, edit: true, delete: true, manage_members: true },
    task: { create: true, edit: true, delete: true, assign: true },
    member: { view_all: true, view_workload: true, manage: true },
    system: { manage_roles: true, view_all_stats: true, manage_settings: true },
  },
};

const memberRole: Role = {
  id: 'role-2',
  name: 'Member',
  description: '일반 팀원',
  isSystem: true,
  permissions: {
    project: { create: false, edit: false, delete: false, manage_members: false },
    task: { create: true, edit: true, delete: false, assign: false },
    member: { view_all: true, view_workload: false, manage: false },
    system: { manage_roles: false, view_all_stats: false, manage_settings: false },
  },
};

// Mock Members
export const mockMembers: Member[] = [
  { id: 'member-1', email: 'admin@example.com', name: '관리자', department: '개발팀', position: '팀장', role: adminRole },
  { id: 'member-2', email: 'hong@example.com', name: '홍길동', department: '개발팀', position: '선임 개발자', role: memberRole },
  { id: 'member-3', email: 'kim@example.com', name: '김철수', department: '디자인팀', position: '디자이너', role: memberRole },
  { id: 'member-4', email: 'lee@example.com', name: '이영희', department: '마케팅팀', position: '팀장', role: memberRole },
];

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'project-1',
    name: '워크플로우 시스템 개발',
    description: '팀 업무 관리를 위한 워크플로우 시스템 개발 프로젝트',
    status: 'ACTIVE',
    startDate: '2024-01-01',
    endDate: '2024-03-31',
    owner: mockMembers[0],
    members: [
      { id: 'pm-1', projectId: 'project-1', memberId: 'member-1', role: 'OWNER', member: mockMembers[0], joinedAt: '2024-01-01' },
      { id: 'pm-2', projectId: 'project-1', memberId: 'member-2', role: 'EDITOR', member: mockMembers[1], joinedAt: '2024-01-01' },
      { id: 'pm-3', projectId: 'project-1', memberId: 'member-3', role: 'EDITOR', member: mockMembers[2], joinedAt: '2024-01-01' },
      { id: 'pm-4', projectId: 'project-1', memberId: 'member-4', role: 'VIEWER', member: mockMembers[3], joinedAt: '2024-01-01' },
    ],
    _count: { tasks: 10 },
    createdAt: '2024-01-01',
    updatedAt: '2024-01-15',
  },
  {
    id: 'project-2',
    name: '모바일 앱 리뉴얼',
    description: '기존 모바일 앱 UI/UX 개선 프로젝트',
    status: 'ACTIVE',
    startDate: '2024-02-01',
    endDate: '2024-05-31',
    owner: mockMembers[1],
    members: [
      { id: 'pm-5', projectId: 'project-2', memberId: 'member-2', role: 'OWNER', member: mockMembers[1], joinedAt: '2024-02-01' },
      { id: 'pm-6', projectId: 'project-2', memberId: 'member-3', role: 'EDITOR', member: mockMembers[2], joinedAt: '2024-02-01' },
    ],
    _count: { tasks: 5 },
    createdAt: '2024-02-01',
    updatedAt: '2024-02-10',
  },
];

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'project-1',
    title: 'DB 스키마 설계',
    description: '워크플로우 시스템의 데이터베이스 스키마를 설계합니다.',
    status: 'DONE',
    priority: 'HIGH',
    assignee: mockMembers[0],
    reporter: mockMembers[0],
    startDate: '2024-01-01',
    dueDate: '2024-01-07',
    order: 1,
    labels: [{ label: { id: 'label-1', name: '기능', color: '#3b82f6', projectId: 'project-1' } }],
    _count: { subtasks: 0, comments: 2 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-01',
    updatedAt: '2024-01-07',
  },
  {
    id: 'task-2',
    projectId: 'project-1',
    title: 'API 엔드포인트 구현',
    description: 'REST API 엔드포인트를 구현합니다.',
    status: 'DONE',
    priority: 'HIGH',
    assignee: mockMembers[1],
    reporter: mockMembers[0],
    startDate: '2024-01-08',
    dueDate: '2024-01-15',
    order: 2,
    labels: [{ label: { id: 'label-1', name: '기능', color: '#3b82f6', projectId: 'project-1' } }],
    _count: { subtasks: 3, comments: 5 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-08',
    updatedAt: '2024-01-15',
  },
  {
    id: 'task-3',
    projectId: 'project-1',
    title: 'UI 디자인 시안 작성',
    description: '메인 화면과 주요 기능의 디자인 시안을 작성합니다.',
    status: 'DONE',
    priority: 'MEDIUM',
    assignee: mockMembers[2],
    reporter: mockMembers[0],
    startDate: '2024-01-05',
    dueDate: '2024-01-12',
    order: 3,
    labels: [],
    _count: { subtasks: 0, comments: 3 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-05',
    updatedAt: '2024-01-12',
  },
  {
    id: 'task-4',
    projectId: 'project-1',
    title: '프론트엔드 컴포넌트 개발',
    description: 'React 컴포넌트를 개발합니다.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    assignee: mockMembers[1],
    reporter: mockMembers[0],
    startDate: '2024-01-16',
    dueDate: '2024-01-25',
    order: 1,
    folderUrl: 'https://drive.google.com/drive/folders/example',
    labels: [{ label: { id: 'label-1', name: '기능', color: '#3b82f6', projectId: 'project-1' } }],
    _count: { subtasks: 5, comments: 8 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-16',
    updatedAt: '2024-01-20',
  },
  {
    id: 'task-5',
    projectId: 'project-1',
    title: '칸반 보드 드래그앤드롭',
    description: '칸반 보드의 드래그앤드롭 기능을 구현합니다.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assignee: mockMembers[1],
    reporter: mockMembers[0],
    startDate: '2024-01-18',
    dueDate: '2024-01-22',
    order: 2,
    labels: [{ label: { id: 'label-1', name: '기능', color: '#3b82f6', projectId: 'project-1' } }],
    _count: { subtasks: 0, comments: 2 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-18',
    updatedAt: '2024-01-20',
  },
  {
    id: 'task-6',
    projectId: 'project-1',
    title: '간트 차트 구현',
    description: '프로젝트 타임라인을 시각화하는 간트 차트를 구현합니다.',
    status: 'TODO',
    priority: 'MEDIUM',
    assignee: mockMembers[1],
    reporter: mockMembers[0],
    startDate: '2024-01-23',
    dueDate: '2024-01-30',
    order: 1,
    labels: [],
    _count: { subtasks: 0, comments: 0 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: 'task-7',
    projectId: 'project-1',
    title: '대시보드 통계 차트',
    description: '대시보드에 표시할 통계 차트를 구현합니다.',
    status: 'TODO',
    priority: 'LOW',
    assignee: mockMembers[2],
    reporter: mockMembers[0],
    startDate: '2024-01-25',
    dueDate: '2024-02-01',
    order: 2,
    labels: [],
    _count: { subtasks: 0, comments: 1 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: 'task-8',
    projectId: 'project-1',
    title: '사용자 테스트',
    description: '개발된 기능에 대한 사용자 테스트를 진행합니다.',
    status: 'TODO',
    priority: 'HIGH',
    assignee: mockMembers[3],
    reporter: mockMembers[0],
    startDate: '2024-02-01',
    dueDate: '2024-02-07',
    order: 3,
    labels: [{ label: { id: 'label-3', name: '긴급', color: '#f97316', projectId: 'project-1' } }],
    _count: { subtasks: 0, comments: 0 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-15',
    updatedAt: '2024-01-15',
  },
  {
    id: 'task-9',
    projectId: 'project-1',
    title: '배포 환경 설정',
    description: '프로덕션 배포를 위한 서버 환경을 설정합니다.',
    status: 'REVIEW',
    priority: 'MEDIUM',
    assignee: mockMembers[0],
    reporter: mockMembers[0],
    startDate: '2024-01-20',
    dueDate: '2024-01-25',
    order: 1,
    labels: [],
    _count: { subtasks: 2, comments: 4 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-20',
    updatedAt: '2024-01-22',
  },
  {
    id: 'task-10',
    projectId: 'project-1',
    title: '문서화 작업',
    description: '프로젝트 문서화 및 README 작성',
    status: 'REVIEW',
    priority: 'LOW',
    assignee: mockMembers[3],
    reporter: mockMembers[0],
    startDate: '2024-01-22',
    dueDate: '2024-01-28',
    order: 2,
    labels: [],
    _count: { subtasks: 0, comments: 1 },
    project: { id: 'project-1', name: '워크플로우 시스템 개발' },
    createdAt: '2024-01-22',
    updatedAt: '2024-01-23',
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  total: 10,
  todo: 3,
  inProgress: 2,
  review: 2,
  done: 3,
  overdue: 1,
  projects: 2,
  members: 4,
};

// Mock Team Progress
export const mockTeamProgress: TeamProgress[] = [
  { id: 'member-1', name: '관리자', department: '개발팀', taskStats: { todo: 0, inProgress: 0, review: 1, done: 1 }, total: 2 },
  { id: 'member-2', name: '홍길동', department: '개발팀', taskStats: { todo: 1, inProgress: 2, review: 0, done: 2 }, total: 5 },
  { id: 'member-3', name: '김철수', department: '디자인팀', taskStats: { todo: 1, inProgress: 0, review: 0, done: 1 }, total: 2 },
  { id: 'member-4', name: '이영희', department: '마케팅팀', taskStats: { todo: 1, inProgress: 0, review: 1, done: 0 }, total: 2 },
];

// Mock Activities
export const mockActivities: ActivityLog[] = [
  {
    id: 'activity-1',
    taskId: 'task-4',
    memberId: 'member-2',
    action: 'updated',
    member: mockMembers[1],
    task: { id: 'task-4', title: '프론트엔드 컴포넌트 개발', project: { id: 'project-1', name: '워크플로우 시스템 개발' } },
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-2',
    taskId: 'task-5',
    memberId: 'member-2',
    action: 'moved',
    member: mockMembers[1],
    task: { id: 'task-5', title: '칸반 보드 드래그앤드롭', project: { id: 'project-1', name: '워크플로우 시스템 개발' } },
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-3',
    taskId: 'task-9',
    memberId: 'member-1',
    action: 'created',
    member: mockMembers[0],
    task: { id: 'task-9', title: '배포 환경 설정', project: { id: 'project-1', name: '워크플로우 시스템 개발' } },
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-4',
    taskId: 'task-3',
    memberId: 'member-3',
    action: 'moved',
    details: { status: 'DONE' },
    member: mockMembers[2],
    task: { id: 'task-3', title: 'UI 디자인 시안 작성', project: { id: 'project-1', name: '워크플로우 시스템 개발' } },
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'activity-5',
    taskId: 'task-2',
    memberId: 'member-2',
    action: 'moved',
    details: { status: 'DONE' },
    member: mockMembers[1],
    task: { id: 'task-2', title: 'API 엔드포인트 구현', project: { id: 'project-1', name: '워크플로우 시스템 개발' } },
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
];

// Current logged in user
export const mockCurrentUser: Member = mockMembers[0];
